spring:
  shell:
    noninteractive:
      primary-command: task 0104

aidevs:
  task:
    task0104:
      file-base-url: ${AIDEVS_TASK_0104_FILE_BASE_URL}
      answer-url: ${AIDEVS_TASK_0104_ANSWER_URL}
