spring:
  shell:
    noninteractive:
      primary-command: task 0101

aidevs:
  task:
    task0101:
      url: ${AIDEVS_TASK_0101_URL}
      username: ${AIDEVS_TASK_0101_USERNAME}
      password: ${AIDEVS_TASK_0101_PASSWORD}
