spring:
  ai:
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT:6334}
        api-key: ${QDRANT_API_KEY}
        collection-name: ${QDRANT_COLLECTION_NAME:ai-devs}
        use-tls: ${QDRANT_USE_TLS:true}
        initialize-schema: true
