spring:
  ai:
    openai:
      chat:
        enabled: false
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false
      image:
        enabled: false
      embedding:
        enabled: false
      moderation:
        api-key: dummy
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        enabled: true
        options:
          model: ${aidevs.model.default}
      embedding:
        enabled: true
        model: ${aidevs.model.embedding}

aidevs:
  model:
    default: llama3.2:3b
    embedding: nomic-embed-text
    image-description: moondream:1.8b
    keywords: ${aidevs.model.default}
    text-cleanup: ${aidevs.model.default}
    title: ${aidevs.model.default}
