spring:
  application:
    name: ai-devs
  main:
    web-application-type: none
  shell:
    context:
      close: true
    interactive:
      enabled: false
    history:
      name: ${logging.file.path}/${spring.application.name}.history.log
  datasource:
    url: "jdbc:sqlite:${aidevs.cache-dir}/aidevs.db"
  exposed:
    generate-ddl: true
  ai:
    openai:
      chat:
        enabled: false
      audio:
        transcription:
          enabled: false
        speech:
          enabled: false
      embedding:
        enabled: false
      image:
        enabled: false
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: pass


aidevs:
  cache-dir: .cache/ai-devs
  downloads-dir: ${aidevs.cache-dir}/downloads
  tmp-dir: ${aidevs.cache-dir}/.tmp
  ollama:
    unload-models-before-local-whisper: true
  api-key: ${AIDEVS_API_KEY}
  submit-flag-url: ${AIDEVS_SUBMIT_FLAG_URL}
  report-url: ${AIDEVS_REPORT_URL}

logging:
  file:
    path: ${aidevs.cache-dir}/logs
    name: ${logging.file.path}/${spring.application.name}
  level:
    root: info
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: trace
    pl.bartek: debug
    pl:
      bartek:
        aidevs:
          config:
            LoggingRestClientInterceptor: trace
