spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: ${aidevs.model.default}
      image:
        enabled: true
      audio:
        transcription:
          enabled: false
      embedding:
        enabled: true
        options:
          model: ${aidevs.model.embedding}

aidevs:
  model:
    default: gpt-4o-mini
    embedding: text-embedding-ada-002
    image-description: gpt-4o
    keywords: gpt-4o
    text-cleanup: gpt-4o
    title: gpt-4o-mini
