spring:
  application:
    name: ai-devs
  main:
    web-application-type: none
  shell:
    context:
      close: true
    interactive:
      enabled: false
    history:
      name: ${logging.file.path}/${spring.application.name}.history.log
  datasource:
    url: "jdbc:sqlite:${aidevs.cache-dir}/aidevs.db"
  exposed:
    generate-ddl: true
  ai:
    openai:
      chat:
        enabled: false
      audio:
        transcription:
          enabled: false
        speech:
          enabled: false
      embedding:
        enabled: false
      image:
        enabled: false
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: pass


aidevs:
  cache-dir: .cache/ai-devs
  downloads-dir: ${aidevs.cache-dir}/downloads
  tmp-dir: ${aidevs.cache-dir}/.tmp
  ollama:
    unload-models-before-local-whisper: true
  api-key: ${AIDEVS_APIKEY}
  submit-flag-url: ${AIDEVS_SUBMITFLAGURL}
  report-url: ${AIDEVS_REPORTURL}
  task:
    poligon:
      data-url: ${AIDEVS_TASK_POLIGON_DATAURL}
      answer-url: ${AIDEVS_TASK_POLIGON_ANSWERURL}
    task0101:
      url: ${AIDEVS_TASK_0101_ROBOTSYSTEM_URL}
      username: ${AIDEVS_TASK_0101_ROBOTSYSTEM_USERNAME}
      password: ${AIDEVS_TASK_0101_ROBOTSYSTEM_PASSWORD}
    task0102:
      api-url: ${AIDEVS_TASK_0102_CONVERSATIONURL}
    task0103:
      data-url: ${AIDEVS_TASK_0103_DATAURL}
    task0104:
      file-base-url: ${AIDEVS_TASK_0104_FILEBASEURL}
      answer-url: ${AIDEVS_TASK_0104_ANSWERURL}
    task0105:
      data-url: ${AIDEVS_TASK_0105_DATAURL}
    task0201:
      data-url: ${AIDEVS_TASK_0201_DATAURL}
    task0203:
      data-url: ${AIDEVS_TASK_0203_DATAURL}
    task0204:
      data-url: ${AIDEVS_TASK_0204_DATAURL}
    task0205:
      data-url: ${AIDEVS_TASK_0205_DATAURL}
      article-url: ${AIDEVS_TASK_0205_ARTICLEURL}
    task0301:
      data-url: ${AIDEVS_TASK_0301_DATAURL}
    task0302:
      data-url: ${AIDEVS_TASK_0302_DATAURL}
      data-password: ${AIDEVS_TASK_0302_DATAPASSWORD}
    task0303:
      api-url: ${AIDEVS_TASK_0303_APIURL}
    task0304:
      data-url: ${AIDEVS_TASK_0304_DATAURL}
      api-url: ${AIDEVS_TASK_0304_APIURL}
    task0402:
      data-url: ${AIDEVS_TASK_0402_DATA_URL}
    task0403:
      base-url: ${AIDEVS_TASK_0403_BASE_URL}
      questions-url: ${AIDEVS_TASK_0403_QUESTIONS_URL}
    task0405:
      data-url: ${AIDEVS_TASK_0405_DATA_URL}
      questions-url: ${AIDEVS_TASK_0405_QUESTIONS_URL}

logging:
  file:
    path: ${aidevs.cache-dir}/logs
    name: ${logging.file.path}/${spring.application.name}
  level:
    root: info
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: trace
    pl.bartek: debug
    pl:
      bartek:
        aidevs:
          config:
            LoggingRestClientInterceptor: trace
