spring:
  ai:
    openai:
      chat:
        enabled: false
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false
      image:
        enabled: false
      embedding:
        enabled: false
      moderation:
        api-key: dummy
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        enabled: true
        options:
          model: ${OLLAMA_DEFAULT_CHAT_MODEL:llama3.2:3b}
      embedding:
        enabled: true

local:
  ollama:
    possible-models: llama3.2:1b,llama3.2:3b,gemma2:2b,llava:7b,phi3:3.8b # a list from docker/docker-compose.yaml
    unload-before-whisper: true
