spring:
  application:
    name: ai-devs
  main:
    web-application-type: none
  shell:
    context:
      close: true
    interactive:
      enabled: false
    history:
      name: ${spring.application.name}.history.log
aidevs:
  cache-dir: .cache/ai-devs/
  api-key: ${AIDEVS_APIKEY}
  task:
    0:
      data-url: ${AIDEVS_TASK_0_DATAURL}
      answer-url: ${AIDEVS_TASK_0_ANSWERURL}
    1:
      robot-system:
          url: ${AIDEVS_TASK_1_ROBOTSYSTEM_URL}
          username: ${AIDEVS_TASK_1_ROBOTSYSTEM_USERNAME}
          password: ${AIDEVS_TASK_1_ROBOTSYSTEM_PASSWORD}
    2:
      conversation-url: ${AIDEVS_TASK_2_CONVERSATIONURL}
    3:
      data-url: ${AIDEVS_TASK_3_DATAURL}
      answer-url: ${AIDEVS_TASK_3_ANSWERURL}
    4:
      file-base-url: ${AIDEVS_TASK_4_FILEBASEURL}
      answer-url: ${AIDEVS_TASK_4_ANSWERURL}
    5:
      data-url: ${AIDEVS_TASK_5_DATAURL}
      answer-url: ${AIDEVS_TASK_5_ANSWERURL}
    0201:
      data-url: ${AIDEVS_TASK_0201_DATAURL}
      answer-url: ${AIDEVS_TASK_0201_ANSWERURL}
logging:
  file:
    name: ${spring.application.name}.log
  pattern:
    console: "" # disable console logging without logback.xml
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
    pl.bartek: debug
    pl:
      bartek:
        aidevs:
          LoggingRestClientInterceptor: debug
