spring:
  application:
    name: ai-devs
  main:
    web-application-type: none
  shell:
    context:
      close: true
    interactive:
      enabled: false
    history:
      name: ${logging.file.path}/${spring.application.name}.history.log
  ai:
    openai:
      chat:
        enabled: false
      audio:
        transcription:
          enabled: false
        speech:
          enabled: false
      embedding:
        enabled: false
      image:
        enabled: false
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: pass

aidevs:
  cache-dir: .cache/ai-devs/
  api-key: ${AIDEVS_APIKEY}
  submit-flag-url: ${AIDEVS_SUBMITFLAGURL}
  task:
    poligon:
      data-url: ${AIDEVS_TASK_POLIGON_DATAURL}
      answer-url: ${AIDEVS_TASK_POLIGON_ANSWERURL}
    0101:
      robot-system:
        url: ${AIDEVS_TASK_0101_ROBOTSYSTEM_URL}
        username: ${AIDEVS_TASK_0101_ROBOTSYSTEM_USERNAME}
        password: ${AIDEVS_TASK_0101_ROBOTSYSTEM_PASSWORD}
    0102:
      conversation-url: ${AIDEVS_TASK_0102_CONVERSATIONURL}
    0103:
      data-url: ${AIDEVS_TASK_0103_DATAURL}
      answer-url: ${AIDEVS_TASK_0103_ANSWERURL}
    0104:
      file-base-url: ${AIDEVS_TASK_0104_FILEBASEURL}
      answer-url: ${AIDEVS_TASK_0104_ANSWERURL}
    0105:
      data-url: ${AIDEVS_TASK_0105_DATAURL}
      answer-url: ${AIDEVS_TASK_0105_ANSWERURL}
    0201:
      data-url: ${AIDEVS_TASK_0201_DATAURL}
      answer-url: ${AIDEVS_TASK_0201_ANSWERURL}
    0203:
      data-url: ${AIDEVS_TASK_0203_DATAURL}
      answer-url: ${AIDEVS_TASK_0203_ANSWERURL}
    0204:
      data-url: ${AIDEVS_TASK_0204_DATAURL}
      answer-url: ${AIDEVS_TASK_0204_ANSWERURL}
    0205:
      data-url: ${AIDEVS_TASK_0205_DATAURL}
      answer-url: ${AIDEVS_TASK_0205_ANSWERURL}
      article-url: ${AIDEVS_TASK_0205_ARTICLEURL}
    0301:
      data-url: ${AIDEVS_TASK_0301_DATAURL}
      answer-url: ${AIDEVS_TASK_0301_ANSWERURL}
    0302:
      data-url: ${AIDEVS_TASK_0302_DATAURL}
      data-password: ${AIDEVS_TASK_0302_DATAPASSWORD}
      answer-url: ${AIDEVS_TASK_0302_ANSWERURL}
    0303:
      api-url: ${AIDEVS_TASK_0303_APIURL}
      answer-url: ${AIDEVS_TASK_0303_ANSWERURL}
    0304:
      data-url: ${AIDEVS_TASK_0304_DATAURL}
      api-url: ${AIDEVS_TASK_0304_APIURL}
      answer-url: ${AIDEVS_TASK_0304_ANSWERURL}
    0401:
      photos-url: ${AIDEVS_TASK_0401_PHOTOS_URL}
    0402:
      answer-url: ${AIDEVS_TASK_0402_ANSWERURL}
      data-url: ${AIDEVS_TASK_0401_DATA_URL}

logging:
  file:
    path: ./logs
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    console: "" # disable console logging without logback.xml
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
    pl.bartek: debug
    pl:
      bartek:
        aidevs:
          pl.bartek.aidevs.config.LoggingRestClientInterceptor: debug
