spring:
  ai:
    openai:
      api-key: dummy
      chat:
        base-url: http://localhost:11434
        options:
          model: llama3.2:3b
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b
        enabled: false
