spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        enabled: true
        options:
          model: ${GROQ_DEFAULT_CHAT_MODEL:llama3.2:3b}
      audio:
        transcription:
          options:
            model: ${GROQ_DEFAULT_AUDIO_TRANSCRIPTION_MODEL:whisper-large-v3-turbo}
      embedding:
        enabled: true
