name: ai-devs

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    # https://stackoverflow.com/a/78501628
    entrypoint: "bash -c '/entrypoint.sh llama3.2:3b gemma2:2b phi3.5:3.8b qwen2.5:3b moondream:1.8b nomic-embed-text'"
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/entrypoint.sh:/entrypoint.sh
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_dbms_security_auth__minimum__password__length=1
      - NEO4J_AUTH=neo4j/pass
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  ollama:
  neo4j-data:
