name: ai-devs

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    # https://stackoverflow.com/a/78501628
    entrypoint: "bash -c '/entrypoint.sh llama3.2:1b llama3.2:3b gemma2:2b llava:7b phi3:3.8b'"
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/entrypoint.sh:/entrypoint.sh
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  ollama:
  postgres:
